### ISSUE TITLE
Questions about porting TWRP for devices with i.MX6 SL

### ISSUE THREAD

**Issue by Nativu5** [Ryogo-Z/tolino_ntx_6sl_twrp#12]
I have a Tolino Vision 2 and a Boyue T65s and am surprised that they both have a i.MX6SL inside. So, I am wondering if it is possible to port your TWRP to T65s？And if it's practical, how can I do it?
I am short of relevant experience and wish you to offer some suggestions. Thanks.

**Comment by Ryogo-X** [comment]
@0x7ffffff I believe it should be fairly easy port TWRP to T65, but I don't have a device myself.
I've tried to to poke T65 a bit with a help from another person that got device, but that was not very productive.
If you want to try, then good starting point would be:

- try all the variants of twrp for i.mx6 devices: [tolino generic](https://github.com/Ryogo-Z/tolino_ntx_6sl_twrp/releases), [tolino shine 3](https://github.com/Ryogo-Z/tolino_shine3_twrp), [new nooks](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/releases);
- if you got any of the TWRPs above boot successfully (by boot I mean that device recognized by adb) then you're in look;
- if none of the above boots you may try to replace kernel and fstab file in those TWRPs with ones from the T65 boot image using something like [Android Image Kitchen](https://forum.xda-developers.com/showthread.php?t=2073775);

That should be the first step.

**Comment by Nativu5** [comment]
> @0x7ffffff I believe it should be fairly easy port TWRP to T65, but I don't have a device myself.
> I've tried to to poke T65 a bit with a help from another person that got device, but that was not very productive.
> If you want to try, then good starting point would be:
> 
> * try all the variants of twrp for i.mx6 devices: [tolino generic](https://github.com/Ryogo-Z/tolino_ntx_6sl_twrp/releases), [tolino shine 3](https://github.com/Ryogo-Z/tolino_shine3_twrp), [new nooks](https://github.com/Ryogo-Z/nook_ntx_6sl_twrp/releases);
> * if you got any of the TWRPs above boot successfully (by boot I mean that device recognized by adb) then you're in look;
> * if none of the above boots you may try to replace kernel and fstab file in those TWRPs with ones from the T65 boot image using something like [Android Image Kitchen](https://forum.xda-developers.com/showthread.php?t=2073775);
> 
> That should be the first step.

Thx, once I have free time I will try to do it.

**Comment by Ryogo-X** [comment]
Not directly relates to Tolino => closed.
