### ISSUE TITLE
Support for Tolino Vision 6

### ISSUE THREAD

**Issue by ironjan** [Ryogo-Z/tolino_ntx_6sl_twrp#16]
This is an issue to collect information about the Tolino Vision 6 and its support by this project. The Tolino Vision 6 was released on 2021-10-26. Any help would be appreciated.

**System information:**
The following information is available on the recovery mode screen and could be useful for freeing this device. 
```
rakutenKobo/E70P14_android/E70P14_android
8.1.0/3a6f932/20210914-065817
[explanation about recovery mode]
[options, see below]

Supported API: 3
```

The device has three buttons: one power button on the back and two page turn buttons on the fron. "up" will refer the page turn button closer to the power button resp. the button that is used to "go up" in recovery mode. 

**Recovery Mode:**
1. Power off the device completely
2.  Press and hold the power button until the screen flashes (ca. 30 seconds)

The recovery mode shows above information and has 5 options:
1. Start the system
2. Wipe data/factory reset
3. View recovery logs
4. Power off
5. Recover the system

From a first experiment, I assume that option 2 is a standard factory reset (keep system updates intact) wheras option 5 uses a recovery image located somewhere on the device (`/emergency`, true factoryreset, i.e. remove system updates).

**Fastboot Mode:**
1. Power off the device completely
2. Press and hold down button and power until the light flashes and turns on, screen stays off (ca 15s).

> I only noticed that fastboot was somehow active when observing `dmesg` output on my Linux machine. On Windows, I was unable to notice anything, probably becuae of missing drivers.

Output of `fastboot devices`:
```
Android Fastboot       Android Fastboot 
```

Other commands:
```
# dmesg
[31944.783042] usb 3-1: new high-speed USB device number 89 using xhci_hcd
[31944.925799] usb 3-1: New USB device found, idVendor=1f3a, idProduct=1010, bcdDevice= 2.00
[31944.925810] usb 3-1: New USB device strings: Mfr=5, Product=1, SerialNumber=2
[31944.925814] usb 3-1: Product: USB Developer
[31944.925819] usb 3-1: Manufacturer: Android Bootloader Interface
[31944.925823] usb 3-1: SerialNumber: Android Fastboot

# fastboot getvar $version_name # actually used the name. "all" was not supported, the only supported ones are as follows
version: 0.5
serialno: 23001635,afd233d...
product: Android Fastboot

# fastboot boot twrp.img
Sending 'boot.img' (7862 KB)                       OKAY [  0.392s]
Booting                                            OKAY [  0.000s]
Finished. Total time: 0.417s
```
Above command does not trigger a boot. The device stays in a broken(?) fastboot state. After disconnecting and reconnecting the device, dmesg loops over different errors:
```
# dmesg
[31421.778996] usb 3-1: USB disconnect, device number 61
[31426.733165] usb 3-1: new high-speed USB device number 62 using xhci_hcd
[31426.856520] usb 3-1: device descriptor read/64, error -71
[31427.086779] usb 3-1: device descriptor read/64, error -71
[31427.316503] usb 3-1: new high-speed USB device number 63 using xhci_hcd
[31427.439937] usb 3-1: device descriptor read/64, error -71
[31427.669932] usb 3-1: device descriptor read/64, error -71
[31427.776614] usb usb3-port1: attempt power cycle
[31428.179835] usb 3-1: new high-speed USB device number 64 using xhci_hcd
[31428.180009] usb 3-1: Device not responding to setup address.
[31428.386654] usb 3-1: Device not responding to setup address.
[31428.593156] usb 3-1: device not accepting address 64, error -71
[31428.716446] usb 3-1: new high-speed USB device number 65 using xhci_hcd
[31428.716647] usb 3-1: Device not responding to setup address.
[31428.923253] usb 3-1: Device not responding to setup address.
[31429.129698] usb 3-1: device not accepting address 65, error -71
[31429.129878] usb usb3-port1: unable to enumerate USB device
```

```
# fastboot reboot recovery
Rebooting into recovery                            OKAY [  0.000s]
Finished. Total time: 1.056s
```
This however boots into the normal Tolino system.

**Comment by Ryogo-X** [comment]
Hello @ironjan.

It is not possible to support Tolino 6 in scope of this project.
Older Tolino books were based on Freescale i.MX6 platform, but Tolino 6 is based on AllWinner B300 platform.
TWRP for Tolino 6 is whole new project worth, but I'm not really willing to take that effort - at least not unless I have this book in my possession, but I don't really have plans to buy it.

**Comment by ironjan** [comment]
@Ryogo-Z thanks for the info. I added everything I found out in case anyone stumbles on this project/issue. As far as I can tell, Tolino unfortunately seems to have disabled/restricted fastboot for this model.

**Comment by Ryogo-X** [comment]
@ironjan thank you. Also, from what you described I can assume that fastboot is working pretty fine.
At least, "broken state" is anticipated behavior when try to boot something that is not bootable on current device (i.e. "fastboot boot twrp.img").

**Comment by Ryogo-X** [comment]
By the way, Xiaomi Duokan is also a B300 based e-book - might be good idea to look if twrp / root / instructions available for it, since it should be pretty easy to adapt them for Tolino 6.

**Comment by ironjan** [comment]
Thank you for the input, @Ryogo-Z.

As soon as I find the time to start working on getting TWRP onto the Tolino Vision 6 and have an own repository ready, I'll post a final update and link in this issue.

**Comment by ironjan** [comment]
A final update, as promised. Unfortunately the Tolino 6's software turned out to be quite... lackluster. I chose to return the device and cannot try to get TWRP on this device 😞

The reader software had massive problems with epubs from [project gutenberg](https://www.gutenberg.org/); 4 out of 5 books had missing pages(!), sometimes completely missing text, or just missing paragraphs (the epubs validated fine with epub checker). The browser was advertised as very privacy friendly and unfortunately their implementation of this included automatic deletion of all login cookies...

**Comment by Ryogo-X** [comment]
@ironjan I plan to buy Nook Glowlight 4 some time later (which is also a B300 based book), it is possible that I may try to port TWRP onto it which also should help to port it to Tolino 6.
