### ISSUE TITLE
Poweroff should clear the screen

### ISSUE THREAD

**Issue by bell07** [Ryogo-Z/tolino_ntx_6sl_twrp#3]
eInk displash show last image if the device is shut down. It will be usefull to clear the screen if the "Shutdown" functionality is used.
Current the device is powered off, but the last TWRP "Restart options" screen is still shown, that leads to assumtion the device is hanging

**Comment by Ryogo-X** [comment]
Can't promise anything, but I'll look into this.

**Comment by Ryogo-X** [comment]
I had a brief look and taking required effort in account I don't think I'm interested in this one.
