### ISSUE TITLE
On-screen keyboards works not very well

### ISSUE THREAD

**Issue by Ryogo-X** [Ryogo-Z/tolino_ntx_6sl_twrp#6]
TWRP built-in on-screen keyboard not recognize single tap for some keyboard keys which makes using keyboard a bit tricky.

**Comment by bell07** [comment]
Tested on my "page" and you are right. 

~50% of key presses have a delay that result in "long key press" alternative character.
Tried to disable the "key vibration" settings. Feels faster but did not solved the issue.

If keys pressed behind each other the issue does happens less common.
If no key is pressed for some seconds, the first key press gets the long-key-press more often

**Comment by Ryogo-X** [comment]
Somewhat input handling is tied to screen refresh. Long screen refresh could produce fake long-presses.
The issue should be fixed in https://github.com/Ryogo-Z/tolino_ntx_6sl_twrp/releases/tag/3.2.3v3 due to enabling A2 mode + new monochrome theme.
