### ISSUE TITLE
Compatibility to stock firmware

### ISSUE THREAD

**Issue by bell07** [Ryogo-Z/tolino_ntx_6sl_twrp#8]
After some playing I decided to take a fresh reinstall. But TWRP is not able to flash the stock firmware. The Error message is 
```
Upgrade : ALL include recovery for 4.0
This package is for tolino devices except shine1!
Updater process ended with ERROR: 7
```

Tried (unsure if the right way) to install the "orig_update.zip" file from inside the update.zip file. Got the message:
`This package is for AOSP 4.4.2: this is "5.1.1"`

Is it possible to get twrp able to install stock firmware? Without them it is difficult to rescue the device if system is broken.

**Comment by juppin** [comment]
I think it would be better to create a modified update.zip file because the original one does also include a recovery.img and then we will overwrite our twrp recovery.

**Comment by bell07** [comment]
Of course I can remove the recovery.img from update.zip, but this does not solve the problem the TWRP is not able to install this update.zip. 
The easiest way for me is just to flash the stock, and then re-install the TWRP. 
Or how I can get any other working zipfile with full system reinstallation.

By the way, is it posssible to compile the AOSP with some more features then stock? The current stock does not have the wallpaper service so it is not possible to set wallpaper in no launcher :-(

**Comment by Ryogo-X** [comment]
**juppin**, I've posted modified update.zip already both for fw 10.x and fw 11.x [here](https://forum.alles-ebook.de/showthread.php/6815-FW-for-TWRP-downgrade).

**bell07**, what you say is a right thing, but I'm not sure I can really do that. The way how tolino did they're install script inside update.zip is causing some difficulties for TWRP and I'm not sure I can mitigate them.

**Comment by juppin** [comment]
> The easiest way for me is just to flash the stock, and then re-install the TWRP.

You can also fastboot the recovery.img from the riginal uodate.zip, update/restore your system and reflash twrp. Is not that much trickier... After that you can backup and restore with twrp.

> By the way, is it posssible to compile the AOSP with some more features then stock?

I think this will be not that easy. 
Sadly longshine does not provide the full source of there android port...
They provide only a link to the google aosp projecct.
I don´t know if it´t wort the effort to create a custom rom from source for this low spec device.
For me modding the stock rom is all that i want.

**Comment by Ryogo-X** [comment]
>By the way, is it posssible to compile the AOSP with some more features then stock?

it would require a good amount of work. Whats **juppin** said is correct - tolino/nook does not provide sources for their AOSP patches and without them there will be no support for eink screen.
I was thinking about this for some time already, but I think I won't have that much of a free time to dig so deep into this.

**Comment by bell07** [comment]
The original recovery is very bad. It does not contain the adb binary, and you have just options "Start the system", "Wipe data" and "Recover the system".
I do not know what the third option does but it did not working for me :-(

**Comment by juppin** [comment]
I will try to contac the manufacturer longshine tomorrow for a more complete aosp and kernel source.
The kernel source does also miss some files.
The website of longshine and there ftp server does not provide any additional gpl sources.

Here the answer of my gpl source email request at tolino.de:

Dear Mr. Neuhauser,

thank you for your message.

Please contact the manufacturer Longshine. The contact details are as follows: 

An der Strusbek 9
22926 Ahrensburg
Phone: 04102 492233 (Mo-Do, 8:30 – 17:30, Fr. 8:30 – 16:00)
Mail: tolino@longshine.de

We hope that we have helped you with this information and are always available for further questions. 


Best regards,

Your thalia.de-Team
i. A. Karl Pommerening

**Comment by Ryogo-X** [comment]
I've actually rechecked possibility of supporting unmodified vendor update.zip and I must say that indeed I see no way to support them.
TWRP uses busybox shell which cannot properly handle unmodified upgrade.sh from update.zip.
Also, 10.x updater-script designed in a way that it is not possible to use it as is to go from 11.x to 10.x.

**Comment by dandygig** [comment]
> **juppin**, I've posted modified update.zip already both for fw 10.x and fw 11.x [here](https://forum.alles-ebook.de/showthread.php/6815-FW-for-TWRP-downgrade).
> 

I finally made it with **your** image to get a bricked Tolion Vision 2 working. Hard.
It works but not very well as some areas are not shown properly.
Is there a way to come back from this image to a original image? I tried to flash a Update.zip (11.2.0 & 11.2.3) to Version 12.2.0 image but this ended up in the usual assertion failed errors.

**Comment by Ryogo-X** [comment]
@dandygig you can flash stock recovery (or, maybe even boot it without flashing using "fastboot boot") and flash 13.x fw.

**Comment by dandygig** [comment]
Did work. Many thanks! Phew.
