### ISSUE TITLE
RxTx Serial Interface on Tolino Vison 4HD

### ISSUE THREAD

**Issue by bobomko** [Ryogo-Z/tolino_ntx_6sl_twrp#9]
Is there any possibiliyty to use one of the serial interfaces on the mainboard of the Tolino Vison 4HD od a Tolino Shine. On a Kobo Mini you can use XCSolar with a GPS receiver (http://blueflyvario.blogspot.com/2014/04/blueflyvariottl-integration-with-kobo.html) I would do this with a Tolino

**Comment by Ryogo-X** [comment]
I don't have an answer for this.
Anyway, it is out of the scope of TWRP porting, so closing it.
